### ISSUE TITLE
System.TypeLoadException:“Could not load type 'App.Metrics.Reporting.Abstractions.IReportFactory' from assembly 'App.Metrics, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812'.”

### ISSUE THREAD

**Issue by kongkong56** [AppMetrics/Reporting#45]
app.UseMetricsReporting(lifetime); 
in 2.0.0,has error:
System.TypeLoadException:“Could not load type 'App.Metrics.Reporting.Abstractions.IReportFactory' from assembly 'App.Metrics, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812'.”

**Comment by alhardy** [comment]
Looks like you have a reference to one of the older packages. Refer to the docs on [aspnet core reporting](https://www.app-metrics.io/web-monitoring/aspnet-core/reporting/), the [sample app](https://github.com/AppMetrics/Samples.V2/tree/master/AspNetCore2.Api.QuickStart), or the [aspnet core sandox app](https://github.com/AppMetrics/AspNetCore/tree/dev/sandbox/MetricsReportingSandboxMvc) in the aspnet core repo.

Hope this helps
